#---- '/etc/auditbeat/auditbeat.yml' -----#

#----- hostmachine : Amend below entries inside 
output.elasticsearch:
  hosts: ["elastic:9200"] # resolve to elastic server from lxc container
  
  username: "elastic" # only, security is enabled
  password: "venkata"

#----- elasticsearch server: configure metricbeat -------#
name: webserver
tags: ["web-tier"]  # replace old tags

setup.dashboards.enabled: true
setup.kibana:
  host: "elastic:5601"

logging.level: debug
logging.selectors: ["*"]
logging.to_files: true
logging.files:
  path: /var/log/auditbeat
  name: auditbeat
  keepfiles: 7
  permissions: 0644

monitoring.enabled: true
monitoring.elasticsearch: 