#----- /etc/metricbeat/modules.d/apache.yml ------#

# Module: apache
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.11/metricbeat-module-apache.html

- module: apache
  metricsets:
    - status
  period: 10s
  hosts: ["http://10.87.217.15"] #["http://127.0.0.1"]
  #username: "user"
  #password: "secret"